### ISSUE TITLE
Add `go-gelf` Room in Gitter

### ISSUE THREAD

**Issue by 0cjs** [Graylog2/go-gelf#12]
There's currently a [graylog2-server](https://gitter.im/Graylog2/graylog2-server) room in Gitter, but it would be nice to have one for [go-gelf](https://gitter.im/Graylog2/go-gelf) as well. Could some [member of the Graylog2 project](https://github.com/orgs/Graylog2/people) create this?

**Comment by mariussturm** [comment]
https://gitter.im/Graylog2/go-gelf should do it.
