### ISSUE TITLE
No exported method for creating TCPReaders

### ISSUE THREAD

**Issue by zbuc** [Graylog2/go-gelf#21]
There is a `newTCPReader` function, however it isn't exported. There doesn't seem to be an exported method of creating TCP-based reader applications that use this library.

https://github.com/Graylog2/go-gelf/blob/v2/gelf/tcpreader.go#L22

**Comment by joschi** [comment]
@zbuc `TCPReader` is just a helper class for the test cases of go-gelf and is not supposed to be exported.

https://github.com/Graylog2/go-gelf/blob/4143646226541087117ff2f83334ea48b3201841/gelf/tcpwriter_test.go#L22

**Comment by zbuc** [comment]
Is there any way of creating a TCP reader instead of UDP? The exported method in Reader.go is only a UDP reader. The readme file for the v2 branch says TCP is supported.

**Comment by joschi** [comment]
@zbuc go-gelf is a GELF *client*  library and doesn't provide any GELF server parts.

**Comment by zbuc** [comment]
Oh. In V1 (and V2) some GELF server parts are exposed (and work fine), but
only for UDP.

On Wed, Feb 28, 2018 at 10:13 AM, Jochen Schalanda <notifications@github.com

**Comment by joschi** [comment]
Maybe @mariussturm would like to add a comment here.

**Comment by mariussturm** [comment]
Like @joschi said, this is a pure _client_ library. The reader parts you see are used exclusively for testing and should not be used in any application project.

**Comment by zbuc** [comment]
FWIW, this code: https://github.com/Graylog2/go-gelf/blob/v2/gelf/reader.go#L24 is publicly exported and works fine for UDP GELF servers from my testing.
